# Generated by Django 2.2 on 2021-07-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210714_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersymptomformmodel',
            name='breath_less_ness',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default=False, max_length=128),
        ),
        migrations.AddField(
            model_name='usersymptomformmodel',
            name='loss_of_test_or_smell',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default=False, max_length=120),
        ),
        migrations.AddField(
            model_name='usersymptomformmodel',
            name='pain',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default=False, max_length=120),
        ),
        migrations.AddField(
            model_name='usersymptomformmodel',
            name='sore_throat',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='cold',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=128),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='cough',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=128),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='fever',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=128),
        ),
    ]
