# Generated by Django 2.2 on 2021-07-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_usersymptomformmodel_oxygen_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersymptomformmodel',
            name='oxygen_level',
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='breath_less_ness',
            field=models.CharField(choices=[(1, 'True'), (0, 'False')], default=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='cold',
            field=models.CharField(choices=[(1, 'True'), (0, 'False')], max_length=128),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='cough',
            field=models.CharField(choices=[(1, 'True'), (0, 'False')], max_length=128),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='fever',
            field=models.CharField(choices=[(1, 'True'), (0, 'False')], max_length=128),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='loss_of_test_or_smell',
            field=models.CharField(choices=[(1, 'True'), (0, 'False')], default=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='pain',
            field=models.CharField(choices=[(1, 'True'), (0, 'False')], default=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='sore_throat',
            field=models.CharField(choices=[(1, 'True'), (0, 'False')], default=False, max_length=120),
        ),
    ]
