# Generated by Django 2.2 on 2021-07-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20210714_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='breath_less_ness',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], default=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='cold',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], max_length=128),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='cough',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], max_length=128),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='fever',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], max_length=128),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='loss_of_test_or_smell',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], default=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='pain',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], default=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='usersymptomformmodel',
            name='sore_throat',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], default=False, max_length=120),
        ),
    ]
